services:
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/src/.env

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: always